# Generated by Django 3.0.3 on 2020-02-29 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databaselist',
            name='active',
        ),
        migrations.RemoveField(
            model_name='databaselist',
            name='created',
        ),
        migrations.RemoveField(
            model_name='tablelist',
            name='active',
        ),
        migrations.RemoveField(
            model_name='tablelist',
            name='created',
        ),
        migrations.AddField(
            model_name='databaselist',
            name='author',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='databaselist',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='databaselist',
            name='full_desription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databaselist',
            name='keywords',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='databaselist',
            name='subject',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tablelist',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='ColumnList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('column_type', models.CharField(max_length=500)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.TableList')),
            ],
        ),
    ]
